USE SCHEMA bronze_layer_db.bronze_layer_schema;

CREATE OR REPLACE TEMPORARY FILE FORMAT tmp_test_fmt TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '\"' SKIP_HEADER = 1 ENCODING = 'WINDOWS1252';

COPY INTO employees
FROM @bronze_sf_gcs_stage
FILE_FORMAT=tmp_test_fmt
FORCE=True
-- FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '\"' SKIP_HEADER = 1 ENCODING = 'WINDOWS1252');
